### ISSUE TITLE
failures when I try to test

### ISSUE THREAD

**Issue by kylak** [jtauber/vocabulary-tools#2]
Eιρήνη שָׁלוֹם

"_Run python -m doctest -v examples.rst to test._" didn't work for me.

<img width="570" alt="Capture d’écran 2020-12-22 à 01 55 16" src="https://user-images.githubusercontent.com/16438248/102836089-bf938a80-43f8-11eb-9e08-d7c97c56383d.png">

**Comment by jtauber** [comment]
very strange. It works fine for me and the error doesn't make sense as `sentences` is defined just a couple of lines above where the error is occurring (unless there's another error earlier).
