### ISSUE TITLE
Question about old/new morphological tags

### ISSUE THREAD

**Issue by aaronshaf** [jtauber/vocabulary-tools#4]
What is the difference between the `morphological tag (old)` and `morphological tag (new)`?

**Comment by jtauber** [comment]
The old tag is the original CCAT tagging scheme.

The new tag is my work-in-progress replacement that uses separate codes for case and gender syncretism.

See https://github.com/morphgnt/sblgnt/wiki/Proposal-for-a-New-Tagging-Scheme for more details.

**Comment by jtauber** [comment]
In particular, see:

* https://github.com/morphgnt/sblgnt/wiki/Proposal-for-Case-Tagging
* https://github.com/morphgnt/sblgnt/wiki/Proposal-for-Gender-Tagging
